apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-mariadb
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mariadb
              key: mariadb-password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wordpress-pvc